// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#include "ui.h"
#include "lv_demos.h"

static lv_obj_t * g_kb_screen;
static void kb_screen_event_cb(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t *kb = lv_event_get_target(e);
	if(code == LV_EVENT_READY || code == LV_EVENT_CANCEL){
		lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
	}
}
static uint8_t tmp_cou;
static void screen_img_2_event_handler(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	switch (code)
	{
	case LV_EVENT_CLICKED:
		if (tmp_cou)
		{
			tmp_cou = 0;
			lv_img_set_src(ui_Image_CT0J2ECT, &ui_img_dengpao_liangnew_png_png);
		}
		else
		{
			tmp_cou = 1;
			lv_img_set_src(ui_Image_CT0J2ECT, &ui_img_dengpao_guannew_png_png);
		}
		printf("!!! clicked\r\n");
		break;
	default:
		break;
	}
}

void ui_Screen_NIYasopN_screen_init(void) {
	ui_Screen_NIYasopN = lv_obj_create(NULL);

	g_kb_screen = lv_keyboard_create(ui_Screen_NIYasopN);
	lv_obj_add_event_cb(g_kb_screen,kb_screen_event_cb,LV_EVENT_ALL,NULL);
	lv_obj_add_flag(g_kb_screen,LV_OBJ_FLAG_HIDDEN);
	lv_obj_set_scrollbar_mode(g_kb_screen,LV_SCROLLBAR_MODE_OFF);
	lv_obj_clear_flag(ui_Screen_NIYasopN,LV_OBJ_FLAG_SCROLLABLE);


	ui_Image_ikmSk3zh = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_ikmSk3zh,240);
	lv_obj_set_height(ui_Image_ikmSk3zh,320);
	lv_obj_set_x(ui_Image_ikmSk3zh,0);
	lv_obj_set_y(ui_Image_ikmSk3zh,0);
	lv_obj_set_style_img_recolor(ui_Image_ikmSk3zh,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_ikmSk3zh,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_ikmSk3zh,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_ikmSk3zh,&ui_img_beijing_png_png);
	lv_img_set_pivot(ui_Image_ikmSk3zh,50,50);
	lv_img_set_angle(ui_Image_ikmSk3zh,0);

	ui_Image_UyZtfQCL = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_UyZtfQCL,105);
	lv_obj_set_height(ui_Image_UyZtfQCL,150);
	lv_obj_set_x(ui_Image_UyZtfQCL,10);
	lv_obj_set_y(ui_Image_UyZtfQCL,155);
	lv_obj_set_style_img_recolor(ui_Image_UyZtfQCL,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_UyZtfQCL,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_UyZtfQCL,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_UyZtfQCL,&ui_img_bianzu_2_png_png);
	lv_img_set_pivot(ui_Image_UyZtfQCL,50,50);
	lv_img_set_angle(ui_Image_UyZtfQCL,0);
    lv_obj_add_flag(ui_Image_UyZtfQCL, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_Image_UyZtfQCL, screen_img_2_event_handler, LV_EVENT_ALL, NULL);

	ui_Image_3wh2Z51M = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_3wh2Z51M,105);
	lv_obj_set_height(ui_Image_3wh2Z51M,70);
	lv_obj_set_x(ui_Image_3wh2Z51M,125);
	lv_obj_set_y(ui_Image_3wh2Z51M,155);
	lv_obj_set_style_img_recolor(ui_Image_3wh2Z51M,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_3wh2Z51M,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_3wh2Z51M,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_3wh2Z51M,&ui_img_beijing_1__png_png);
	lv_img_set_pivot(ui_Image_3wh2Z51M,50,50);
	lv_img_set_angle(ui_Image_3wh2Z51M,0);

	ui_Image_VFPOs3dR = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_VFPOs3dR,105);
	lv_obj_set_height(ui_Image_VFPOs3dR,70);
	lv_obj_set_x(ui_Image_VFPOs3dR,125);
	lv_obj_set_y(ui_Image_VFPOs3dR,235);
	lv_obj_set_style_img_recolor(ui_Image_VFPOs3dR,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_VFPOs3dR,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_VFPOs3dR,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_VFPOs3dR,&ui_img_beijing_1__png_png);
	lv_img_set_pivot(ui_Image_VFPOs3dR,50,50);
	lv_img_set_angle(ui_Image_VFPOs3dR,0);

	ui_Image_pnQ0GsuI = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_pnQ0GsuI,32);
	lv_obj_set_height(ui_Image_pnQ0GsuI,32);
	lv_obj_set_x(ui_Image_pnQ0GsuI,162);
	lv_obj_set_y(ui_Image_pnQ0GsuI,163);
	lv_obj_set_style_img_recolor(ui_Image_pnQ0GsuI,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_pnQ0GsuI,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_pnQ0GsuI,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_pnQ0GsuI,&ui_img_shuimian_png_png);
	lv_img_set_pivot(ui_Image_pnQ0GsuI,50,50);
	lv_img_set_angle(ui_Image_pnQ0GsuI,0);

	ui_Image_d36uDDdK = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_d36uDDdK,32);
	lv_obj_set_height(ui_Image_d36uDDdK,32);
	lv_obj_set_x(ui_Image_d36uDDdK,161);
	lv_obj_set_y(ui_Image_d36uDDdK,243);
	lv_obj_set_style_img_recolor(ui_Image_d36uDDdK,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_d36uDDdK,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_d36uDDdK,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_d36uDDdK,&ui_img_qichuang_png_png);
	lv_img_set_pivot(ui_Image_d36uDDdK,50,50);
	lv_img_set_angle(ui_Image_d36uDDdK,0);

	ui_Image_2naRiCAM = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_2naRiCAM,36);
	lv_obj_set_height(ui_Image_2naRiCAM,22);
	lv_obj_set_x(ui_Image_2naRiCAM,10);
	lv_obj_set_y(ui_Image_2naRiCAM,15);
	lv_obj_set_style_img_recolor(ui_Image_2naRiCAM,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_2naRiCAM,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_2naRiCAM,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_2naRiCAM,&ui_img_xingzhuangjiehe_png_png);
	lv_img_set_pivot(ui_Image_2naRiCAM,50,50);
	lv_img_set_angle(ui_Image_2naRiCAM,0);

	ui_Label__q79u838 = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label__q79u838,65);
	lv_obj_set_y(ui_Label__q79u838,16);
	lv_obj_set_width(ui_Label__q79u838,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label__q79u838,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label__q79u838,"Guangzhou");
	lv_obj_set_style_text_color(ui_Label__q79u838,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label__q79u838,204,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label__q79u838,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label__q79u838,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_xps9oCLZ = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_xps9oCLZ,170);
	lv_obj_set_y(ui_Label_xps9oCLZ,16);
	lv_obj_set_width(ui_Label_xps9oCLZ,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_xps9oCLZ,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_xps9oCLZ,"cloudy");
	lv_obj_set_style_text_color(ui_Label_xps9oCLZ,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_xps9oCLZ,204,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_xps9oCLZ,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_xps9oCLZ,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_P7flpD1x = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_P7flpD1x,11);
	lv_obj_set_y(ui_Label_P7flpD1x,41);
	lv_obj_set_width(ui_Label_P7flpD1x,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_P7flpD1x,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_P7flpD1x,"12:00:00");
	lv_obj_set_style_text_color(ui_Label_P7flpD1x,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_P7flpD1x,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_P7flpD1x,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_P7flpD1x,&lv_font_montserrat_48,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_zmZKi2al = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_zmZKi2al,11);
	lv_obj_set_y(ui_Label_zmZKi2al,111);
	lv_obj_set_width(ui_Label_zmZKi2al,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_zmZKi2al,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_zmZKi2al,"Aug 8th Tues");
	lv_obj_set_style_text_color(ui_Label_zmZKi2al,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_zmZKi2al,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_zmZKi2al,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_zmZKi2al,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_xp_YZTZM = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_xp_YZTZM,39);
	lv_obj_set_y(ui_Label_xp_YZTZM,248);
	lv_obj_set_width(ui_Label_xp_YZTZM,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_xp_YZTZM,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_xp_YZTZM,"Switch");
	lv_obj_set_style_text_color(ui_Label_xp_YZTZM,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_xp_YZTZM,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_xp_YZTZM,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_xp_YZTZM,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_Ezbnyzvk = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_Ezbnyzvk,150);
	lv_obj_set_y(ui_Label_Ezbnyzvk,197);
	lv_obj_set_width(ui_Label_Ezbnyzvk,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_Ezbnyzvk,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_Ezbnyzvk,"sleep");
	lv_obj_set_style_text_color(ui_Label_Ezbnyzvk,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_Ezbnyzvk,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_Ezbnyzvk,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_Ezbnyzvk,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Label_hAWbFFty = lv_label_create(ui_Screen_NIYasopN);
	lv_obj_set_x(ui_Label_hAWbFFty,149);
	lv_obj_set_y(ui_Label_hAWbFFty,279);
	lv_obj_set_width(ui_Label_hAWbFFty,LV_SIZE_CONTENT);
	lv_obj_set_height(ui_Label_hAWbFFty,LV_SIZE_CONTENT);
	lv_label_set_text(ui_Label_hAWbFFty,"daytime");
	lv_obj_set_style_text_color(ui_Label_hAWbFFty,lv_color_hex(0xFFFFFF),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_Label_hAWbFFty,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Label_hAWbFFty,LV_TEXT_ALIGN_CENTER,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label_hAWbFFty,&lv_font_montserrat_14,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Panel_c8ugW8kb = lv_obj_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Panel_c8ugW8kb,2);
	lv_obj_set_height(ui_Panel_c8ugW8kb,8);
	lv_obj_set_x(ui_Panel_c8ugW8kb,61);
	lv_obj_set_y(ui_Panel_c8ugW8kb,292);
	lv_obj_set_style_pad_left(ui_Panel_c8ugW8kb,0,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui_Panel_c8ugW8kb,0,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui_Panel_c8ugW8kb,0,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui_Panel_c8ugW8kb,0,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_scroll_dir(ui_Panel_c8ugW8kb,LV_DIR_VER);
	lv_obj_set_style_radius(ui_Panel_c8ugW8kb,0,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_Panel_c8ugW8kb,lv_color_hex(0x69D35F),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_Panel_c8ugW8kb,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Panel_c8ugW8kb,lv_color_hex(0x69D35F),LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_opa(ui_Panel_c8ugW8kb,255,LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Panel_c8ugW8kb,1,LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Image_CT0J2ECT = lv_img_create(ui_Screen_NIYasopN);
	lv_obj_set_width(ui_Image_CT0J2ECT,64);
	lv_obj_set_height(ui_Image_CT0J2ECT,64);
	lv_obj_set_x(ui_Image_CT0J2ECT,30);
	lv_obj_set_y(ui_Image_CT0J2ECT,172);
	lv_obj_set_style_img_recolor(ui_Image_CT0J2ECT,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_recolor_opa(ui_Image_CT0J2ECT,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_img_opa(ui_Image_CT0J2ECT,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_img_set_src(ui_Image_CT0J2ECT,&ui_img_dengpao_guannew_png_png);
	lv_img_set_pivot(ui_Image_CT0J2ECT,50,50);
	lv_img_set_angle(ui_Image_CT0J2ECT,0);

	// ui_Image_eEloi_Te = lv_img_create(ui_Screen_NIYasopN);
	// lv_obj_set_width(ui_Image_eEloi_Te,64);
	// lv_obj_set_height(ui_Image_eEloi_Te,64);
	// lv_obj_set_x(ui_Image_eEloi_Te,30);
	// lv_obj_set_y(ui_Image_eEloi_Te,172);
	// lv_obj_set_style_img_recolor(ui_Image_eEloi_Te,lv_color_make(0xff, 0xff, 0xff),LV_PART_MAIN|LV_STATE_DEFAULT);
	// lv_obj_set_style_img_recolor_opa(ui_Image_eEloi_Te,0,LV_PART_MAIN|LV_STATE_DEFAULT);
	// lv_obj_set_style_img_opa(ui_Image_eEloi_Te,255,LV_PART_MAIN|LV_STATE_DEFAULT);
	// lv_img_set_src(ui_Image_eEloi_Te,&ui_img_dengpao_liangnew_png_png);
	// lv_img_set_pivot(ui_Image_eEloi_Te,50,50);
	// lv_img_set_angle(ui_Image_eEloi_Te,0);
}
