// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_Screen_NIYasopN
void ui_Screen_NIYasopN_screen_init(void);
lv_obj_t * ui_Screen_NIYasopN;
lv_obj_t * ui_Image_ikmSk3zh;
lv_obj_t * ui_Image_UyZtfQCL;
lv_obj_t * ui_Image_3wh2Z51M;
lv_obj_t * ui_Image_VFPOs3dR;
lv_obj_t * ui_Image_pnQ0GsuI;
lv_obj_t * ui_Image_d36uDDdK;
lv_obj_t * ui_Image_2naRiCAM;
lv_obj_t * ui_Label__q79u838;
lv_obj_t * ui_Label_xps9oCLZ;
lv_obj_t * ui_Label_P7flpD1x;
lv_obj_t * ui_Label_zmZKi2al;
lv_obj_t * ui_Label_xp_YZTZM;
lv_obj_t * ui_Label_Ezbnyzvk;
lv_obj_t * ui_Label_hAWbFFty;
lv_obj_t * ui_Panel_c8ugW8kb;
lv_obj_t * ui_Image_CT0J2ECT;
lv_obj_t * ui_Image_eEloi_Te;
lv_obj_t * ui____initial_actions0;



///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void) {
	lv_disp_t * dispp = lv_disp_get_default();
	lv_theme_t * theme = lv_theme_default_init(dispp,
		lv_palette_main(LV_PALETTE_BLUE),
		lv_palette_main(LV_PALETTE_RED),
		false,
		LV_FONT_DEFAULT);
	lv_disp_set_theme(dispp, theme);
	ui_Screen_NIYasopN_screen_init();
	ui____initial_actions0 = lv_obj_create(NULL);
	lv_disp_load_scr(ui_Screen_NIYasopN);
}
