// This file was generated by iot-lvgl-service
// LVGL version: 8.3.6

#ifndef _PROJECT_UI_H
#define _PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen_NIYasopN
void ui_Screen_NIYasopN_screen_init(void);
extern lv_obj_t * ui_Screen_NIYasopN;
extern lv_obj_t * ui_Image_ikmSk3zh;
extern lv_obj_t * ui_Image_UyZtfQCL;
extern lv_obj_t * ui_Image_3wh2Z51M;
extern lv_obj_t * ui_Image_VFPOs3dR;
extern lv_obj_t * ui_Image_pnQ0GsuI;
extern lv_obj_t * ui_Image_d36uDDdK;
extern lv_obj_t * ui_Image_2naRiCAM;
extern lv_obj_t * ui_Label__q79u838;
extern lv_obj_t * ui_Label_xps9oCLZ;
extern lv_obj_t * ui_Label_P7flpD1x;
extern lv_obj_t * ui_Label_zmZKi2al;
extern lv_obj_t * ui_Label_xp_YZTZM;
extern lv_obj_t * ui_Label_Ezbnyzvk;
extern lv_obj_t * ui_Label_hAWbFFty;
extern lv_obj_t * ui_Panel_c8ugW8kb;
extern lv_obj_t * ui_Image_CT0J2ECT;
extern lv_obj_t * ui_Image_eEloi_Te;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_beijing_1__png_png);
LV_IMG_DECLARE(ui_img_beijing_png_png);
LV_IMG_DECLARE(ui_img_bianzu_2_png_png);
LV_IMG_DECLARE(ui_img_dengpao_guannew_png_png);
LV_IMG_DECLARE(ui_img_dengpao_liangnew_png_png);
LV_IMG_DECLARE(ui_img_qichuang_png_png);
LV_IMG_DECLARE(ui_img_shuimian_png_png);
LV_IMG_DECLARE(ui_img_xingzhuangjiehe_png_png);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
